[auth]
site_url = "https://echyklzjuxogkdqydpjw.supabase.co"
additional_redirect_urls = [
  "https://echyklzjuxogkdqydpjw.supabase.co",
  "https://echyklzjuxogkdqydpjw.supabase.co/auth/callback",
  "https://dojolibre.netlify.app",
  "https://dojolibre.com"
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"